const $=id=>document.getElementById(id);
const clean=t=>String(t||'').replace(/[\u201C\u201D]/g,'"').replace(/[\u2018\u2019]/g,"'").replace(/[\u2013\u2014]/g,'-').replace(/[•●▪‣⁃*]/g,'-').replace(/[<>]/g,'').replace(/&/g,'E').replace(/https?:\/\/\S+/gi,'').replace(/Chave de acesso:\s*\S+/gi,'').replace(/Resultado completo acesse:\s*\S+/gi,'').replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE00}-\u{FE0F}]/gu,'').replace(/[^\S\r\n]+/g,' ').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
const up=t=>clean(t).toUpperCase();
const na=v=>clean(v)||'NA';
const fmtLines=x=>{x=up(x);if(!x)return '- NA';return x.split('\n').map(s=>clean(s)).filter(Boolean).map(s=>s.startsWith('-')?s:'- '+s).join('\n')};
const state={modo:'EVOLUÇÃO',qp:'',acomp:'DESACOMPANHADO(A)',desc:'',tempo:'',assoc:'',sec:'',nega:'',medcont:'',comorb:'',alerg:'',fc:'',fr:'',sat:'',tax:'',pa:'',hgt:'',dor:'',geral:'',acv:'',ar:'',abd:'',neuro:'',mmii:'',outros:'',hd:'',conduta:'',status:'',emtempo:'',excomp:'',raw:'',red:{}};
const redFlags=['DOR TORÁCICA','DISPNEIA','SÍNCOPE','DÉFICIT FOCAL','REBAIXAMENTO','INSTABILIDADE HEMODINÂMICA','FEBRE PERSISTENTE','SANGRAMENTO','VÔMITOS INCOERCÍVEIS','DEFESA/RIGIDEZ/BLUMBERG','GESTAÇÃO','IMUNOSSUPRESSÃO'];
const sx=['DOR ABDOMINAL','DOR EPIGÁSTRICA','NÁUSEAS','VÔMITOS','DIARREIA','FEBRE','CEFALEIA','TONTURA','DOR TORÁCICA','DISPNEIA','TOSSE','ODINOFAGIA','DISÚRIA','LOMBALGIA','PALPITAÇÕES','SUDORESE','IRRADIAÇÃO','PARESTESIA'];
const cond=['MEDICAÇÃO SINTOMÁTICA','ANALGESIA','ANTIEMÉTICO','ANTITÉRMICO','HIDRATAÇÃO EV','HIDRATAÇÃO VO','EXAMES LABORATORIAIS','ECG','TROPONINA','RX','TC','USG','EAS','PARECER ESPECIALISTA','OBSERVAÇÃO CLÍNICA','REAVALIAÇÃO APÓS MEDICAÇÃO','ALTA COM ORIENTAÇÕES','INTERNAÇÃO SOLICITADA'];
const statusList=['ALTA','AGUARDA EXAMES','AGUARDA PARECER','OBSERVAÇÃO CLÍNICA','SALA VERMELHA','INTERNAÇÃO SOLICITADA'];
let active='nota', userEdited=false;
function card(title,open,fn){const c=document.createElement('div');c.className='card'+(open?'':' closed');const h=document.createElement('div');h.className='head';h.innerHTML='<h2>'+title+'</h2><span class="chev">▼</span>';h.onclick=()=>c.classList.toggle('closed');const b=document.createElement('div');b.className='body';fn(b);c.append(h,b);return c}
function inp(label,key,ph=''){const l=document.createElement('label');l.innerHTML='<span>'+label+'</span>';const i=document.createElement('input');i.value=state[key]||'';i.placeholder=ph;i.oninput=()=>{state[key]=i.value;refresh()};l.append(i);return l}
function area(label,key,ph=''){const l=document.createElement('label');l.innerHTML='<span>'+label+'</span>';const i=document.createElement('textarea');i.value=state[key]||'';i.placeholder=ph;i.oninput=()=>{state[key]=i.value;refresh()};l.append(i);return l}
function chip(text,on,cb,rf=false){const s=document.createElement('span');s.className='chip '+(rf?'rf ':'')+(on?'on':'');s.textContent=text;s.onclick=()=>{cb(!s.classList.contains('on'));render();refresh()};return s}
function group(t){const d=document.createElement('div');d.className='group';d.textContent=t;return d}
function render(){const f=$('form');f.innerHTML='';f.append(card('1 · Modo de nota',true,b=>{const m=document.createElement('div');m.className='mode';['EVOLUÇÃO','REAVALIAÇÃO'].forEach(x=>{const bt=document.createElement('button');bt.textContent=x;bt.className=state.modo===x?'on':'';bt.onclick=()=>{state.modo=x;render();refresh()};m.append(bt)});b.append(m)}));
f.append(card('2 · QP e HDA',true,b=>{b.append(inp('QP em linha única','qp','ex.: DOR ABDOMINAL'),inp('Acompanhamento','acomp','ACOMPANHADO(A) / DESACOMPANHADO(A)'),area('Descrição da queixa','desc','ex.: dor em flanco esquerdo, progressiva, sem irradiação'),inp('Tempo','tempo','ex.: 2 DIAS / 6 HORAS'),area('Sintomas associados','assoc','ex.: náuseas, vômitos, febre'),area('Queixas secundárias / refere também','sec','ex.: refere também...'),area('Nega / red flags negativas','nega','ex.: nega febre, vômitos, disúria, sangramento, dispneia'),group('Chips rápidos de sintomas'));const g=document.createElement('div');g.className='chips';sx.forEach(x=>g.append(chip(x,false,v=>{state.assoc=clean((state.assoc?state.assoc+', ':'')+x)})));b.append(g,group('Red flags de segurança'));const r=document.createElement('div');r.className='chips';redFlags.forEach(x=>r.append(chip(x,!!state.red[x],v=>state.red[x]=v,true)));b.append(r)}));
f.append(card('3 · HPP e medicações',false,b=>{b.append(area('Comorbidades','comorb','NA se ausente'),area('Alergias','alerg','NA se ausente'),area('Medicações de uso contínuo','medcont','Pode deixar linhas em branco para completar à mão'))}));
f.append(card('4 · Sinais vitais',false,b=>{const r1=document.createElement('div');r1.className='row';r1.append(inp('FC','fc'),inp('FR','fr'),inp('STO2','sat'));const r2=document.createElement('div');r2.className='row';r2.append(inp('TAX','tax'),inp('PA','pa','120/80'),inp('HGT','hgt'),inp('DOR 0-10','dor'));b.append(r1,r2)}));
f.append(card('5 · Exame físico',false,b=>{b.append(area('GERAL','geral','BEG, LOTE, HIDRATADO(A), EUPNEICO(A)...'),area('ACV','acv','RCR 2T, BNF, SEM SOPROS'),area('AR','ar','MV PRESENTE BILATERALMENTE, SEM RA'),area('ABD','abd','ABD FLÁCIDO, DOLOROSO/INDOLOR À PALPAÇÃO, SEM IRRITAÇÃO PERITONEAL'),area('NEUROLÓGICO','neuro','GLASGOW 15, SEM DÉFICIT FOCAL, PUPILAS...'),area('MMII - pesquisa de TVP','mmii','SEM EDEMA, PANTURRILHAS LIVRES, SEM EMPASTAMENTO, PULSOS...'),area('OUTROS - PSIQ/TEGUMENTAR/ORO/OTO','outros','NA ou achados específicos'))}));
f.append(card('6 · Hipótese e conduta',false,b=>{b.append(area('Hipótese diagnóstica - múltiplas linhas','hd','- DOR ABDOMINAL A ESCLARECER\n- ...'),area('Conduta - múltiplas linhas','conduta','- EXAMES LABORATORIAIS\n- MEDICAÇÃO SINTOMÁTICA'));const g=document.createElement('div');g.className='chips';cond.forEach(x=>g.append(chip(x,false,v=>{state.conduta=clean((state.conduta?state.conduta+'\n':'')+'- '+x)})));b.append(group('Condutas rápidas'),g)}));
f.append(card('7 · Reavaliação / EM TEMPO / Status',false,b=>{b.append(area('EM TEMPO da reavaliação','emtempo','ex.: paciente reavaliado após medicação, refere melhora...'),area('Exames complementares já formatados','excomp','Cole aqui o resultado do transformador, se desejar'),group('Status do atendimento'));const s=document.createElement('div');s.className='status';statusList.forEach(x=>{const bt=document.createElement('button');bt.textContent=x;bt.className=state.status===x?'on':'';bt.onclick=()=>{state.status=state.status===x?'':x;render();refresh()};s.append(bt)});b.append(s)}));
f.append(card('8 · Transformador de exames',true,b=>{b.append(area('Cole o exame cru aqui','raw','Laboratório, TC, RX, ECG/laudo...'));const bt=document.createElement('button');bt.className='btn coral';bt.textContent='Transformar exames';bt.onclick=()=>{active='exames';document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('on',t.dataset.tab===active));userEdited=false;refresh()};b.append(bt)}));}
function medBlock(){let m=up(state.medcont);if(!m||m==='NA')return '- MEDICAÇÕES DE USO CONTÍNUO:\n  - NA\n  - \n  - ';return '- MEDICAÇÕES DE USO CONTÍNUO:\n'+m.split(/\n|;/).filter(Boolean).map(x=>'  - '+up(x)).join('\n')+'\n  - \n  - '}
function hda(){let qp=up(state.qp)||'[QUEIXA]';let p='PACIENTE COMPARECE AO PS, '+up(state.acomp||'DESACOMPANHADO(A)')+' COM QUEIXA DE '+qp;if(state.desc)p+=' DE '+up(state.desc);p+=' HÁ '+(up(state.tempo)||'[TEMPO]');if(state.assoc)p+=', ASSOCIADO A '+up(state.assoc);p+='.';if(state.sec)p+=' REFERE TAMBÉM '+up(state.sec).replace(/\.$/,'')+'.';if(state.nega)p+=' NEGA '+up(state.nega).replace(/^NEGA\s+/,'').replace(/\.$/,'')+'.';else p+=' NEGA DEMAIS QUEIXAS.';return p}
function vit(){return ['- FC: '+(state.fc?up(state.fc)+' BPM':'NA'),'- FR: '+(state.fr?up(state.fr)+' IRPM':'NA'),'- STO2: '+(state.sat?up(state.sat)+'%':'NA'),'- TAX: '+(state.tax?up(state.tax)+' C':'NA'),'- PA: '+(state.pa?up(state.pa)+' MMHG':'NA'), state.hgt?'- HGT: '+up(state.hgt):'', state.dor?'- DOR: '+up(state.dor)+'/10':''].filter(Boolean).join('\n')}
function exam(){return ['- GERAL: '+na(up(state.geral)),'- ACV: '+na(up(state.acv)),'- AR: '+na(up(state.ar)),'- ABD: '+na(up(state.abd)),'- NEUROLÓGICO: '+na(up(state.neuro)),'- MMII: '+na(up(state.mmii)),'- OUTROS: '+na(up(state.outros))].join('\n')}
function nota(){let t=[];t.push('## '+state.modo+' PRONTO SOCORRO - HOSPITAL MERIDIONAL SERRA ##','');t.push('# QP: "'+(up(state.qp)||'[QUEIXA PRINCIPAL]')+'"','');t.push('# HDA:'); if(state.modo==='REAVALIAÇÃO'){t.push('HDA DA ADMISSÃO: '+hda(),'');t.push('# EM TEMPO:');t.push(na(up(state.emtempo)));}else t.push(hda());t.push('','# HPP:','- COMORBIDADES: '+na(up(state.comorb)),'- ALERGIAS: '+na(up(state.alerg)),medBlock(),'','# SINAIS VITAIS:',vit(),'','# EXAME FÍSICO:',exam());if(state.modo==='REAVALIAÇÃO'){t.push('','# EXAMES COMPLEMENTARES:',na(up(state.excomp||transformExams(state.raw))))}t.push('','# HIPÓTESE DIAGNÓSTICA:',fmtLines(state.hd),'','# CONDUTA:',fmtLines(state.conduta));return clean(t.join('\n'))}
function adc(){const s=up(state.status)||'[STATUS]';let base='PACIENTE REAVALIADO(A), HEMODINAMICAMENTE ESTÁVEL NO MOMENTO, SEM SINAIS DE INSTABILIDADE CLÍNICA IMEDIATA. '+(state.emtempo?up(state.emtempo)+' ':'');if(/ALTA/.test(s))base+='APRESENTA CONDIÇÕES CLÍNICAS PARA ALTA NO MOMENTO. ORIENTADOS SINAIS DE ALARME, RETORNO IMEDIATO SE PIORA, ADESÃO À PRESCRIÇÃO E SEGUIMENTO AMBULATORIAL. ALTA MÉDICA.';else base+='MANTIDO(A) EM '+s+' PARA SEGUIMENTO, REAVALIAÇÃO E DEFINIÇÃO DE CONDUTA.';return clean(base)}
function passagem(){return clean(['SITUAÇÃO:','- PACIENTE EM '+(up(state.status)||'ATENDIMENTO')+' POR '+(up(state.qp)||'[QUEIXA]')+'.','','BACKGROUND:','- '+hda(),'- COMORBIDADES: '+na(up(state.comorb))+'.','','AVALIAÇÃO:','- SINAIS VITAIS: FC '+na(up(state.fc))+' / FR '+na(up(state.fr))+' / STO2 '+na(up(state.sat))+' / PA '+na(up(state.pa))+' / TAX '+na(up(state.tax))+'.','- HD: '+na(up(state.hd)).replace(/\n/g,'; ')+'.','','RECOMENDAÇÃO:',fmtLines(state.conduta)].join('\n'))}
function valAfter(label,t){const re=new RegExp(label+'\\s+([0-9][0-9.,]*)','i');const m=t.match(re);return m?m[1]:''}
function transformExams(raw){let t=clean(raw);if(!t)return '';let out=[];if(/HEMOGRAMA|Hemoglobina|Leucócitos|Plaquetas/i.test(t)){let hb=valAfter('Hemoglobina',t),ht=valAfter('Hematócrito',t),leu=valAfter('Leucócitos',t),bast=valAfter('Bastonetes',t),seg=valAfter('Segmentados',t),plaq=(t.match(/Contagem de Plaquetas\s+([0-9.]+)/i)||[])[1];let hemo=[];if(hb)hemo.push('HB '+hb);if(ht)hemo.push('HT '+ht);if(leu)hemo.push('LEUCO '+leu);if(bast)hemo.push('BAST '+bast+'%');if(seg)hemo.push('SEG '+seg+'%');if(plaq)hemo.push('PLAQ '+plaq);if(hemo.length)out.push('- HEMOGRAMA: '+hemo.join(' / ')+'.')}
let cr=(t.match(/CREATININA[\s\S]{0,100}?RESULTADO\s+([0-9.,]+)/i)||[])[1];let rfg=(t.match(/TAXA FILTRAÇÃO GLOMERULAR\s+([^\n.]+(?:mL\/min[^\s]*)?)/i)||[])[1];if(cr||rfg)out.push('- FUNÇÃO RENAL: CREATININA '+(cr||'NA')+(rfg?' / RFG '+clean(rfg):'')+'.');let ureia=(t.match(/UREIA\s+([0-9.,]+)\s*mg\/dL/i)||[])[1];if(ureia)out.push('- UREIA: '+ureia+' MG/DL.');let tgp=(t.match(/TRANSAMINASE GLUTAMICO PIRUVICA[\s\S]{0,100}?RESULTADO\s+([0-9.,]+)/i)||[])[1];let tgo=(t.match(/TRANSAMINASE GLUTAMICO OXALACETICA[\s\S]{0,100}?RESULTADO\s+([0-9.,]+)/i)||[])[1];if(tgo||tgp)out.push('- TRANSAMINASES: TGO '+(tgo||'NA')+' / TGP '+(tgp||'NA')+'.');let pcr=(t.match(/PROTEINA "?C"? REATIVA[\s\S]{0,100}?RESULTADO\s+([0-9.,]+)/i)||[])[1];if(pcr)out.push('- PCR: '+pcr+' MG/L.');let ami=(t.match(/AMILASE SERICA[\s\S]{0,100}?RESULTADO\s+([0-9.,]+)/i)||[])[1];let lip=(t.match(/LIPASE[\s\S]{0,100}?RESULTADO\s+([0-9.,]+)/i)||[])[1];if(ami||lip)out.push('- ENZIMAS PANCREÁTICAS: AMILASE '+(ami||'NA')+' / LIPASE '+(lip||'NA')+'.');if(/EAS|ELEMENTOS ANORMAIS|SEDIMENTO URINARIO/i.test(t)){let ph=(t.match(/pH\s+([0-9.,]+)/i)||[])[1],dens=(t.match(/DENSIDADE\s+([0-9.]+)/i)||[])[1],prot=(t.match(/PROTEINA\s+(\+\+\+|\+\+|\+|Não detectado|Normal)/i)||[])[1],nit=(t.match(/NITRITO\s+([^\s]+(?: Detectado)?)/i)||[])[1],leuc=(t.match(/LEUCOCITO\s+([^\s]+(?: Detectado)?)/i)||[])[1],pio=(t.match(/PIOCITOS\s+([0-9]+)/i)||[])[1],hem=(t.match(/HEMACIAS\s+([^\s]+)/i)||[])[1],flora=(t.match(/FLORA BACTERIANA\s+([^\n]+?)\s+(?:Escassa|Ausente|CRISTAIS|Método)/i)||[])[1];out.push('- EAS: PH '+(ph||'NA')+' / DENSIDADE '+(dens||'NA')+' / PROTEÍNA '+(prot||'NA')+' / NITRITO '+(nit||'NA')+' / LEUCÓCITO '+(leuc||'NA')+' / PIÓCITOS '+(pio||'NA')+' / HEMÁCIAS '+(hem||'NA')+' / FLORA '+clean(flora||'NA')+'.')}
if(/TOMOGRAFIA/i.test(t)){let title=(t.match(/TOMOGRAFIA[^\n]+?(?= TÉCNICA| TECNICA|$)/i)||[])[0]||'TOMOGRAFIA';let imp=(t.match(/IMPRESSÃO DIAGNÓSTICA\s+([\s\S]*?)(?:Resultado completo|Responsável técnico|$)/i)||[])[1];out.push('- '+up(title)+': '+(imp?up(imp):'LAUDO DESCRITIVO COLADO. REVISAR IMPRESSÃO DIAGNÓSTICA.')+'.')}
if(/RX|RAIO|TÓRAX|TORAX/i.test(t)&&/INTERPRETAÇÃO|INTERPRETACAO/i.test(t)){let title=(t.match(/RX[^:]+/i)||[])[0]||'RX';let inter=(t.match(/INTERPRETAÇ(?:ÃO|AO):\s*([\s\S]*?)$/i)||[])[1];out.push('- '+up(title)+': '+(inter?up(inter):'REVISAR LAUDO')+'.')}
if(/ECG|ELETROCARDIOGRAMA/i.test(t)){let imp=(t.match(/(?:CONCLUSÃO|CONCLUSAO|INTERPRETAÇÃO|INTERPRETACAO|LAUDO)[:\s]+([\s\S]*?)$/i)||[])[1]||t;out.push('- ECG: '+up(imp)+'.')}
return clean(out.join('\n'))||'- EXAMES COMPLEMENTARES: NÃO FOI POSSÍVEL TRANSFORMAR AUTOMATICAMENTE. REVISAR TEXTO CRU.'}
function refresh(){let txt=active==='nota'?nota():active==='exames'?transformExams(state.raw):active==='adc'?adc():passagem();if(!userEdited)$('out').value=txt;$('alert').classList.toggle('show',!!Object.values(state.red).find(Boolean)&&/ALTA/i.test(state.status));$('hint').textContent=active==='exames'?'Cole exames crus no formulário e use o transformador. Saída já vem em padrão de evolução.':'Texto editável antes de copiar.'}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{active=t.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===t));userEdited=false;refresh()});$('out').oninput=()=>userEdited=true;$('regen').onclick=()=>{userEdited=false;refresh()};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('out').value)}catch(e){$('out').select();document.execCommand('copy')}const b=$('copy');b.textContent='Copiado';b.classList.add('ok');setTimeout(()=>{b.textContent='Copiar';b.classList.remove('ok')},1300)};$('reset').onclick=()=>{if(confirm('Resetar tudo?')){Object.keys(state).forEach(k=>{if(k==='modo')state[k]='EVOLUÇÃO';else if(k==='acomp')state[k]='DESACOMPANHADO(A)';else if(k==='red')state[k]={};else state[k]=''});render();refresh()}};$('expand').onclick=()=>document.querySelectorAll('.card').forEach(c=>c.classList.remove('closed'));$('collapse').onclick=()=>document.querySelectorAll('#form .card').forEach(c=>c.classList.add('closed'));
render();refresh();